export const SELECT_FORM_IN_ROW = 'SELECT_FORM_IN_ROW';
export const SAVE_FORM = 'SAVE_FORM';
export const CHANGE_BOARD_TITLE = 'CHANGE_BOARD_TITLE';


export const CHANGE_FORM_TITLE = 'CHANGE_FORM_TITLE';
export const ADD_NEW_FORM_BLOCK = 'ADD_FORM_BLOCK';
export const REMOVE_FORM_BLOCK = ' DELETE_FORM_BLOCK';
